<form class="form custom-block"
      id="custom-block-form"
      method="post"
>
	<div class="actions-toolbar">
		<div class="primary">
			<button class="action primary checkout" type="submit" title="Assembler" id="submit">
				<span>Send Inquiry</span>
			</button>
		</div>
	</div>
	<div class="response-output"></div>
</form>

<script type="text/javascript">
require(["jquery"], function($) {
	$("#submit").click(function(e){
		var customer_email = $('#customer-email').val();
		var name = $('input[name="firstname"]').val();
                    
	 	e.preventDefault();
		var customurl = "<?php echo $this->getUrl('game/flow/sendmail')?>";
		$.ajax({
			url: customurl,
			type: 'POST',
			dataType: 'json',
			data : {
				email : customer_email,
				name : name
			},
			showLoader: true,
			
			success: function(response) { 
				$(".response-output").html("<div class=response-output>"+response.output.message+"</div>");
			},
			error: function (xhr, status, errorThrown) {
			    console.log('Error happens. Try again.');
			}
		});  
	});
});

</script>