<?php 

// echo "<pre>";
// $productCOllection = $block->getProductAsPartType("Keyboard","",true);
// print_r($productCOllection->getData());
// exit;

?>
<?php $imageUrl = $block->getPlacehodlerImageUrl(); ?>
<div class="row response">
	<div class="col-md-6">
    	<h1>Tweak Hardware</h1>
    	<h2 class="lead mb-4 mt-4 primary">Primary Components</h2>
    	<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image cpu-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								CPU
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="cpu-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price cpu-mrp-price" id="cpu-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="cpu-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price cpu-rod-price" id="cpu-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="cpu" onchange="getDynamicData('cpu');getSelectedData('cpu');">
						<?php foreach ($block->getProductAsPartType("CPU",true) as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="cpuHelp" class="cpu-description"></small>
				<a href="#" class="action-more-info hide cpu-more-info text-light"  id="cpu-more-info" data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image motherboard-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Motherboard
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="motherboard-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price motherboard-mrp-price" id="motherboard-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="motherboard-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price motherboard-rod-price" id="motherboard-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="motherboard" onchange="getDynamicData('motherboard')">
						<?php foreach ($block->getProductAsPartType("Motherboard") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="motherboardHelp" class="motherboard-description"></small>
				<a href="#" class="action-more-info hide motherboard-more-info text-light"  id="motherboard-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image gpu-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								GPU
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="gpu-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price gpu-mrp-price" id="gpu-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="gpu-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price gpu-rod-price" id="gpu-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="gpu" onchange="getDynamicData('gpu')">
						<?php foreach ($block->getProductAsPartType("GPU",true) as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>

				</div>
				<small id="gpuHelp" class="gpu-description"></small>
				<a href="#" class="action-more-info hide gpu-more-info text-light"  id="gpu-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image memory-image" alt="..." />
			<div class="media-body col-10 pl-0">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-3">
							<label for="memorySelect" class="hw-label">
								Memory
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="memory-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price memory-mrp-price" id="memory-mrp-price" value="" />
						</div>
						<div class="col-5 align-self-end">
							<div class="memory-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price memory-rod-price" id="memory-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="memory" onchange="getDynamicData('memory')">
						<?php foreach ($block->getProductAsPartType("Memory",true) as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="memoryHelp" class="memory-description"></small>
				<a href="#" class="action-more-info hide memory-more-info text-light"  id="memory-more-info"  data-more-info="">More Info</a>
			</div>
			<div class="col-2 memory-increment-qty">
				<div class="media-body">
					<div class="form-group">
						<div class="row justify-content-between">
							<div class="col">
								<label for="memorySelect" class="hw-label">
									Qty
								</label>
							</div>
						</div>
						<select class="memory-qty form-control action-change-qty" id="memory-qty" onchange="getDynamicData('memory-qty')" data-role="Memory">
							<?php 
								for ($i=1; $i <= 4; $i++) { 
							?>
								<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
		</div>		
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image case-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Case
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="case-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price case-mrp-price" id="case-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="case-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price case-rod-price" id="case-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="case" onchange="getDynamicData('case');getSelectedData('case');">
						<?php foreach ($block->getProductAsPartType("Case") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="caseHelp" class="case-description"></small>
				<a href="#" class="action-more-info hide case-more-info text-light"  id="case-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image cooling-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Cooling
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="cooling-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price cooling-mrp-price" id="cooling-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="cooling-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price cooling-rod-price" id="cooling-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="cooling" onchange="getDynamicData('cooling')">
						<?php foreach ($block->getProductAsPartType("Cooling") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="coolingHelp" class="cooling-description"></small>
				<a href="#" class="action-more-info hide cooling-more-info text-light"  id="cooling-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image power-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Power
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="power-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price power-mrp-price" id="power-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="power-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price power-rod-price" id="power-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="power" onchange="getDynamicData('power')">
						<?php foreach ($block->getProductAsPartType("Power") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="powerHelp" class="power-description"></small>
				<a href="#" class="action-more-info hide power-more-info text-light"  id="power-more-info"  data-more-info="">More Info</a>
			</div>
		</div>		
		<h2 class="lead mt-5 mb-4 storage">Storage (Please select any 1 / both from the HDD & SSD options)</h2>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image hdd-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-3">
							<label for="HDDSelect" class="hw-label">
								HDD
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="hdd-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price hdd-mrp-price" id="hdd-mrp-price" value="" />
						</div>
						<div class="col-5 align-self-end">
							<div class="hdd-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price hdd-rod-price" id="hdd-rod-price" value="" />
						</div>
					</div>
					<select required class="form-control action-auto-update-hw storage-component" id="hdd" onchange="getDynamicData('hdd')">
						<option value="">None</option>
						<?php foreach ($block->getProductAsPartType("Storage HDD") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="keyboardHelp" class="hdd-description"></small>
				<a href="#" class="action-more-info hide hdd-more-info text-light"  id="hdd-more-info"  data-more-info="">More Info</a>
			</div>
			<div class="col-2 hdd-increment-qty">
				<div class="media-body">
					<div class="form-group">
						<div class="row justify-content-between">
							<div class="col">
								<label for="hddSelect" class="hw-label">
									Qty
								</label>
							</div>
						</div>
						<select class="hdd-qty form-control action-change-qty" id="hdd-qty" onchange="getDynamicData('hdd-qty')" data-role="Storage HDD">
							<?php 
								for ($i=1; $i <= 5; $i++) { 
							?>
								<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image ssd-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-3">
							<label for="ssdSelect" class="hw-label">
								SSD
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="ssd-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price ssd-mrp-price" id="ssd-mrp-price" value="" />
						</div>
						<div class="col-5 align-self-end">
							<div class="ssd-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price ssd-rod-price" id="ssd-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw storage-component" id="ssd" onchange="getDynamicData('ssd')" required>
						<option value="">None</option>
						<?php foreach ($block->getProductAsPartType("Storage SSD") as $product): ?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<small id="keyboardHelp" class="ssd-description"></small>
				<a href="#" class="action-more-info hide ssd-more-info text-light"  id="ssd-more-info"  data-more-info="">More Info</a>
			</div>
			<div class="col-2 ssd-increment-qty">
				<div class="media-body">
					<div class="form-group">
						<div class="row justify-content-between">
							<div class="col">
								<label for="ssdSelect" class="hw-label">
									Qty
								</label>
							</div>
						</div>
						<select class="ssd-qty form-control action-change-qty" id="ssd-qty" onchange="getDynamicData('ssd-qty')" data-role="Storage SSD">
							<?php 
								for ($i=1; $i <= 5; $i++) { 
							?>
								<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
			</div>
		</div>
		<h2 class="lead mt-5 mb-4">Optional</h2>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image keyboard-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Keyboard
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="keyboard-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price keyboard-mrp-price" id="keyboard-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="keyboard-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price keyboard-rod-price" id="keyboard-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="keyboard" onchange="getDynamicData('keyboard')">
						<option value="">None</option>
						<?php $Keyboard = 0; ?>
						<?php foreach ($block->getProductAsPartType("Keyboard","",true) as $product): 
							$Keyboard ++;
							if($Keyboard == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="keyboardHelp" class="keyboard-description"></small>
				<a href="#" class="action-more-info hide keyboard-more-info text-light"  id="keyboard-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image mice-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Mice
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="mice-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price mice-mrp-price" id="mice-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="mice-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price mice-rod-price" id="mice-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="mice" onchange="getDynamicData('mice')">
						<option value="">None</option>
						<?php $Mice = 0; ?>
						<?php foreach ($block->getProductAsPartType("Mice","",true) as $product): 
							$Mice ++;
							if($Mice == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="miceHelp" class="mice-description"></small>
				<a href="#" class="action-more-info hide mice-more-info text-light"  id="mice-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image gamepad-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Gamepad
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="gamepad-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price gamepad-mrp-price" id="gamepad-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="gamepad-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price gamepad-rod-price" id="gamepad-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="gamepad" onchange="getDynamicData('gamepad')">
						<option value="">None</option>
						<?php $Gamepad = 0; ?>
						<?php foreach ($block->getProductAsPartType("Gamepad","",true) as $product): 
							$Gamepad ++;
							if($Gamepad == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="gamepadHelp" class="gamepad-description"></small>
				<a href="#" class="action-more-info hide gamepad-more-info text-light"  id="gamepad-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image display-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Display
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="display-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price display-mrp-price" id="display-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="display-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price display-rod-price" id="display-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="display" onchange="getDynamicData('display')">
						<option value="">None</option>
						<?php $Display = 0; ?>
						<?php foreach ($block->getProductAsPartType("Display","",true) as $product): 
							$Display ++;
							if($Display == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="displayHelp" class="display-description"></small>
				<a href="#" class="action-more-info hide display-more-info text-light" id="display-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image audio-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="motherboardSelect" class="hw-label">
								Audio
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="audio-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price audio-mrp-price" id="audio-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="audio-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price audio-rod-price" id="audio-rod-price" value="" />
						</div>
					</div>
					<select class="form-control action-auto-update-hw" id="audio" onchange="getDynamicData('audio')"> 
						<option value="">None</option>
						<?php $Audio = 0; ?>
						<?php foreach ($block->getProductAsPartType("Audio","",true) as $product): 
							$Audio ++;
							if($Audio == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="audioHelp" class="audio-description"></small>
				<a href="#" class="action-more-info hide audio-more-info text-light" id="audio-more-info" data-more-info="">More Info</a>
			</div>
		</div>
		<div class="media mb-4">
			<img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image operating-system-image-image" alt="..." />
			<div class="media-body">
				<div class="form-group">
					<div class="row justify-content-between">
						<div class="col-4">
							<label for="OSSelect" class="hw-label">
								Operating System
							</label>
						</div>
						<div class="col-4 align-self-end">
							<div class="operating-system-image-price text-right hw-label"></div>
							<input type="hidden" name="mrp-price" class="mrp-price operating-system-image-mrp-price" id="operating-system-image-mrp-price" value="" />
						</div>
						<div class="col-4 align-self-end">
							<div class="operating-system-image-special-price text-right hw-label"></div>
							<input type="hidden" name="rod-price" class="rod-price operating-system-image-rod-price" id="operating-system-image-rod-price" value="" />
						</div>
					</div>
					<select required class="form-control action-auto-update-hw" id="operating-system-image" onchange="getDynamicData('operating-system-image')">
						<option value="">None</option>
						<?php $operatingSystem = 0; ?>
						<?php foreach ($block->getProductAsPartType("Operating System","",true) as $product): 
							$operatingSystem ++;
							if($operatingSystem == 1){
						?>
							<option value="<?php echo $product->getId(); ?>" selected="selected"><?php echo $product->getName(); ?></option>
						<?php 
							}else{
						?>
							<option value="<?php echo $product->getId(); ?>"><?php echo $product->getName(); ?></option>
						<?php		
							}	
						?>
						<?php endforeach ?>
					</select>
				</div>
				<small id="keyboardHelp" class="operating-system-image-description"></small>
				<a href="#" class="action-more-info hide operating-system-image-more-info text-light"  id="operating-system-image-more-info"  data-more-info="">More Info</a>
			</div>
		</div>
		
	</div>

	<div class="col-md-6 right-block">
		<h2 class="text-center">FPS For Selected Games</h2>
		<div class="row justify-content-center mt-5">
			<?php 
				$fpsArray = [];
				$selectedGamesIds = $block->getSelectedGames();
				foreach($selectedGamesIds as $games):
					$product = $block->loadProductById($games);
					$fpsArray[] = $product->getName();
			?>
					<div class="col-6 col-sm-auto mb-4">
						<div class="card game-card" id="<?php echo ucwords($product->getName()); ?>">
							<img src="<?php echo $block->getImageUrl($product->getImage()); ?>" alt="<?php echo $product->getName(); ?>" />
							<div class="card-body game-card-body">
								<h3 class="card-title game-card-title"><?php echo ucwords($product->getName()); ?></h3>
								<p class="lead">
									FPS : <output
									class="game-fps-output"
									data-game-id="<?php echo strtoupper($product->getName()); ?>-fps"
									></output>
								</p>
							</div>
						</div>
					</div>
			<?php 
				endforeach;
			?>
			<input type="hidden" class="mrppriceValue">
			<input type="hidden" class="rodpriceValue">			
			<div id="sticky_price" class="price-block">
				<span class=rod_price id="rod_price"></span>
				<span class=rod_special_price id="rod_special_price"></span>
			</div>
		</div>
		<input type="hidden" name="fps_game" id="fps_game" value="<?php echo implode(',',$fpsArray); ?>"/>
	</div>

</div>
<div class="gap"></div>
<button class="btn btn-primary btn-lg" id="checkoutAction">Checkout</button>
<?php $siteUrl = $this->getUrl().'pub/static/frontend/Solwin/freego/en_US/images/loader-1.gif'; ?>
<div class="loading" id="loading-image" style="display: none;">
	<img src="<?php echo $siteUrl; ?>"  >
</div>
<section
  class="modal fade"
  id="exampleModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Details</h5>
        <button
          type="button"
          class="close close-modal"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="media mb-2">
          <img src="<?php echo $imageUrl; ?>" class="mr-3 hw-image-large modal-image" alt="..." />
          <div class="media-body">
            <h5 class="modal-title mb-4 text-light"></h5>
            <dl class="">
              <dt>Description</dt>
              <dd>
                <p class="modal-description lead"></p>
              </dd>

             <!--  <dt>Price</dt>
              <dd>
                <p class="modal-price lead"></p>
              </dd>
              <dt>Special Price</dt>
              <dd>
                <p class="modal-special-price lead"></p>
              </dd> -->
            </dl>
          </div>
        </div>
      </div>
      <!-- <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary close-modal"
          data-dismiss="modal"
        >
          Close
        </button>
        
      </div> -->
    </div>
  </div>
</section>

<script>
function getSelectedData(id){
	var params = {
			productid : jQuery('#'+id).val(),
			fieldid : id
		};
	jQuery('#loading-image').show();
	jQuery.ajax({
			url: "/game/flow/compatibility",
			data: params,
			type: "POST",
			dataType: "json",
			success: function(data) {
				jQuery('#loading-image').hide();
				if(data.motherboardHtml){
					var select = jQuery('#motherboard');
					select.empty().append("'"+data.motherboardHtml+"'");
					getDynamicData('motherboard');
				}
				if(data.coolingHtml){
					var select = jQuery('#cooling');
					select.empty().append("'"+data.coolingHtml+"'");
					getDynamicData('cooling');
				}
			}
		}); 
}
function getDynamicData(id) {
	var matches = "-qty";
	var array = id.split(matches);
	var params = '';
	var currencySymbol = "<?php echo $block->getCurrencySymbol(); ?>";
	if(id == 'gpu'){
		params = {
			productid: jQuery('#'+id).val(),
			fpsgame : jQuery('input[name=fps_game]').val()
		};
	}else if(id == array[0]+'-qty'){
		params = {
			productid: jQuery('#'+array[0]).val(),
			qty : jQuery('#'+id).val()
		};
	}else{
		var qty = '';
		if(id+'-qty'){
			var qty = jQuery('#'+id+'-qty').val();
		}
		params = {
			productid: jQuery('#'+id).val(),
			qty : qty
		};
	}
	if(jQuery('#'+id).val()){
		jQuery('#loading-image').show();
		jQuery.ajax({
			url: "/game/flow/products",
			data: params,
			type: "POST",
			dataType: "json",
			success: function(data) {
				var image_url = data.output.image_url;
				var price = data.output.price;
				var name = data.output.name;
				var description = data.output.description;
				var special_price = data.output.special_price;
				jQuery("."+id+"-more-info").css("display","block");
				jQuery('.modal-title').html(name);
				//jQuery('.modal-price').html(price);
				jQuery("."+id+"-rod-price").val(data.output.rod_price);
				jQuery("."+id+"-mrp-price").val(data.output.mrp_price);
				if(description){
					jQuery('.modal-description').html(description);
				}else{
					jQuery('.modal-description').html('');
				}
				
				if(special_price){
					//jQuery('.modal-special-price').html(special_price);
					jQuery("."+id+"-price").html("<strike> MRP "+price+"</strike>");
					jQuery("."+id+"-special-price").html("ROD Price "+special_price);
				}else{
					//jQuery('.modal-special-price').html('');
					jQuery("."+id+"-price").html("MRP "+price);
				}

				if(image_url){
					jQuery("."+id+"-image").attr("src", image_url);	
					jQuery('.modal-image').attr('src', image_url);
				}else{
					var image_url = "<?php echo $imageUrl; ?>";
					jQuery("."+id+"-image").attr("src", image_url);
					jQuery('.modal-image').attr('src', image_url);
				}

				if(data.output.fps){
					jQuery.each(data.output.fps, function(k, v) {	
						var fps=jQuery("[data-game-id='"+v[0]+"-fps']");
						fps.text(v[1]);
					});
				}
				if(data.output.qty){
					if(data.output.special_price){
						jQuery('.'+array[0]+'-special-price').html("ROD Price "+data.output.special_price);
						jQuery('.'+array[0]+'-price').html("<strike> MRP "+data.output.price+"</strike>");
					}else{
						jQuery('.'+array[0]+'-special-price').html('');
						jQuery('.'+array[0]+'-price').html("MRP "+data.output.price);
					}
					jQuery('.'+array[0]+'-rod-price').val(data.output.rod_price);
					jQuery('.'+array[0]+'-mrp-price').val(data.output.mrp_price);
					jQuery('.modal-title').html(data.output.name);
					//jQuery('.modal-price').html(data.output.price);
					if(data.output.image_url){
						jQuery('.'+array[0]+'-image').attr("src", data.output.image_url);	
						jQuery('.modal-image').attr('src', data.output.image_url);
					}else{
						var image_url = "<?php echo $imageUrl; ?>";
						jQuery('.'+array[0]+'-image').attr("src", image_url);
						jQuery('.modal-image').attr('src', image_url);
					}
					if(data.output.description){
						jQuery('.modal-description').html(data.output.description);
					}else{
						jQuery('.modal-description').html('');
					}
				}
				jQuery('#loading-image').hide();
				
				var mrp_price = 0;
				jQuery('.mrp-price').each(function() {
					mrp_price += Number(jQuery(this).val());
				});
				
				jQuery('.rod_price').html("MRP :- <b>"+currencySymbol+mrp_price.toLocaleString('en')+"</b>");
				jQuery('.mrppriceValue').val(mrp_price.toLocaleString('en'));
				
				var rod_price = 0;	
				jQuery('.rod-price').each(function() {
					rod_price += Number(jQuery(this).val());
				});
				
				jQuery('.rod_special_price').html("ROD Price :- <b>"+currencySymbol+rod_price.toLocaleString('en')+"</b>");
				jQuery('.rodpriceValue').val(rod_price.toLocaleString('en'));
			}
		}); 
	}else{
		console.log('data not found');
		var image_url = "<?php echo $imageUrl; ?>";
		jQuery("."+id+"-price").html("");
		jQuery("."+id+"-special-price").html("");
		jQuery("."+id+"-image").attr("src", image_url);
		jQuery("."+id+"-more-info").css("display","none");
		jQuery('.modal-title').html();
		// jQuery('.modal-price').html();
		// jQuery('.modal-special-price').html();
		jQuery('.modal-image').attr('src', image_url);
		jQuery('.modal-description').html('');
		jQuery("."+id+"-rod-price").val(0);
		jQuery("."+id+"-mrp-price").val(0);
		var mrp_price = 0;
		jQuery('.mrp-price').each(function() {
			if(jQuery(this).val()){
				mrp_price += Number(jQuery(this).val());
			}	
		});

		jQuery('.rod_price').html("MRP :- "+currencySymbol+mrp_price.toLocaleString('en'));
		jQuery('.mrppriceValue').val(mrp_price.toLocaleString('en'));

		var rod_price = 0;	
		jQuery('.rod-price').each(function() {
			if(jQuery(this).val()){
				rod_price += Number(jQuery(this).val());
			}
		});
		jQuery('.rod_special_price').html("ROD Price :- "+currencySymbol+rod_price.toLocaleString('en'));
		jQuery('.rodpriceValue').val(rod_price.toLocaleString('en'));
	}
	
}

function removeModal() {
  jQuery(".modal").removeClass("show").css('display','none');
}

function showModal() {
  jQuery(".modal").addClass("show").css('display','block');
}
require(['jquery'], function($) {
	$('.action-auto-update-hw').each(function() {
		var id = $(this).attr('id');
		getSelectedData($(this).attr('id'));
		if(id != 'motherboard' && id != 'cooling'){
			getDynamicData($(this).attr('id'));
		}
	});
	
	$('#checkoutAction').on('click',function(event) {
		var array = [];
		$(".storage-component").each(function(){
			if($(this).val()){
				array.push($(this).val());
			}
		});
		//console.log(array.length);
		if(array.length <= 0){
			alert('Please select any 1 / both from the HDD & SSD options');
			event.preventDefault();
		}else{
			var rodpriceValue = $('.rodpriceValue').val();
			var mrppriceValue = $('.mrppriceValue').val();			
			var selectedProductIds = [];
			$(".action-auto-update-hw").each(function(){
				selectedProductIds.push($(this).val());
			});
			var quantityProductIds = [];
			$('.action-change-qty').each(function() {
				var id = $(this).attr('id');
				var matches = "-qty";
				var array = id.split(matches);
				var qty = jQuery('#'+id).val();
				var productid = jQuery('#'+array[0]).val();
				var label = $(this).attr('data-role');
				quantityProductIds.push({
					label : label, 
					qty : qty,
					productId : productid
				});
			});
			
			$('#loading-image').show();
			$.ajax({
				url: "/game/flow/addtocart",
				data: {
					selectedproductid: selectedProductIds,
					rodpriceValue:rodpriceValue,
					mrppriceValue:mrppriceValue,
					qty : quantityProductIds
				},
				type: "POST",
				dataType: "json",
				showLoader: true,
				success: function(data) {
					$('#loading-image').hide();
					window.location = "/checkout/index/index";
				}
			}); 
		}
		
	});

	

	$(".action-more-info").on('click',function(e) {
		e.preventDefault();
		var str = $(this).attr('id');
		var matches = "-more-info";
		var array = str.split(matches);
		//var array = str.split("-");
		getDynamicData(array[0]);
		// var USERNAME="rfcportal";
		// var PASSWORD="pass123";
		// $.ajax({
		// 	type: "GET",
		// 	dataType: "json",
		// 	url: "https://49.248.160.161:44300/sap/opu/odata/sap/ZSTCOK1_API_SRV_01/GetstockSet?$filter=(Lgort eq 'SDEL' and Matnr eq 'FS608' and Werks eq '1100')&$format=json",
		// 	headers: {
		// 		'Authorization': 'Basic  rfcportal:pass123',
		// 	},
		// 	showLoader: true,
		// 	success: function(data) {
		// 		console.log(data);
		// 	}
		// }); 
		showModal();

	});
	$(".close-modal").on("click", removeModal);
});

// sticky price
require([ "jquery" ], function($){

$(window).scroll(function () {
    if( $(window).scrollTop() > $('#sticky_price').offset().top && !($('#sticky_price').hasClass('sticky'))){
    $('#sticky_price').addClass('sticky');
    } else if ($(window).scrollTop() == 0){
    $('#sticky_price').removeClass('sticky');
    }
});
});
</script>

<style type="text/css">
	.modal-body .media-body {
		overflow: auto;
		max-height: 300px;
	}
</style>