<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */
?>
<?php $_order = $block->getOrder() ?>
<input type="hidden" name="order_id" value="<?= (int) $_order->getId() ?>"/>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Additional Information')) ?></span>
    </div>
        <div class="admin__page-section-item order-information">
           <table class="admin__table-secondary order-information-table">
                <?php if($_order->getSalesPersonCode()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Sales Person Code')) ?></th>
                        <td><?= $_order->getSalesPersonCode() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getStoreName()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Store Name')) ?></th>
                        <td><?= $_order->getStoreName() ?></td>
                    </tr>
                <?php } ?>
                <?php 
                    if($_order->getUserId()){ 
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $customerFactory = $objectManager->get('\Magento\Customer\Model\CustomerFactory')->create();
                        $customer = $customerFactory->load($_order->getUserId());
                        $userName = $customer->getFirstname()." ".$customer->getLastname();
                    ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Created By')) ?></th>
                        <td><?= $userName ?></td>
                    </tr>
                <?php } ?>        
                <?php if($_order->getContainerType()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Container Type')) ?></th>
                        <td><?= $_order->getContainerType() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getContainerSize()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Container Size')) ?></th>
                        <td><?= $_order->getContainerSize() ?></td>
                    </tr>
                <?php } ?>                        
            </table>
        </div>
        <div class="admin__page-section-item order-account-information">
            <table class="admin__table-secondary order-information-table">
                <?php if($_order->getTotalWeight()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Weight')) ?></th>
                        <td><?= $_order->getTotalWeight() ?></td>
                    </tr>           
                <?php } ?>  
                <?php if($_order->getTotalCube()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Volume')) ?></th>
                        <td><?= $_order->getTotalCube() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getDeviceId()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Device Id')) ?></th>
                        <td><?= $_order->getDeviceId() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getLocalAppOrderId()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Local App Order Id')) ?></th>
                        <td><?= $_order->getLocalAppOrderId() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getCustomerAccountNumber()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Account Number')) ?></th>
                        <td><?= $_order->getCustomerAccountNumber() ?></td>
                    </tr>
                <?php } ?>
                <?php if($_order->getErpOrderNumber()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Erp Order Number')) ?></th>
                        <td><?= $_order->getErpOrderNumber() ?></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-secondary order-information-table">
                <tr></tr>
                <?php if($_order->getCustomerNote()){ ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Notes')) ?></th>
                        <td style="text-align:left"><?= $_order->getCustomerNote() ?></td>
                    </tr>
                <?php } ?>
            </table>
        </div>   
</section>

